### ISSUE TITLE
add osx and linux builds to release artifacts

### ISSUE THREAD

**Issue by nclack** [acquire-project/cpx#98]
We've got automated builds on windows (see `.github/workflows/build.rs`), but it would be nice to add for linux and osx now that we've got better cross-platform support.

I think this is the rough todo:

- [ ] add osx and linux to matrix in `build.rs`
- [ ] automatically generate a github Release on tag. Something so that it pops up in ["Releases"](https://github.com/calliphlox/cpx/releases) or ["Packages"](https://github.com/orgs/calliphlox/packages?repo_name=cpx) sections of the sidebar on callphlox/cpx

**Comment by aliddell** [comment]
This is done, actually.
